### ISSUE TITLE
Vapour run not closing down properly using Ctrl +C

### ISSUE THREAD

**Issue by baxtercr** [vapor/toolbox#65] opened 2016-09-04 18:53 UTC
Using vapor v0.10.0

Start server using 'vapour run serve'

close server using 'Ctrl + C'

the server does not actually shutdown .  Noticed also that mongkitten connection is not closed either.

**Comment by tannernelson** [comment] 2016-09-05 14:47
Duplicate of vapor/toolbox#68

**Closed by tannernelson** 2016-09-05 14:47 UTC
