### ISSUE TITLE
Automatic code generation for Fluent

### ISSUE THREAD

**Issue by brunobl** [vapor/toolbox#176] opened 2017-05-25 18:01 UTC
It would be great to enhance vapor cli to add something similar to phx.gen, ie automatic code generator for model and controller based on a quick model description.

http://www.phoenixframework.org/docs/ecto-models

At least the phx.gen.api side at first would be useful. (their documentation isn't up to date, it's now called phx.gen.api instead of phoenix.gen.api)

**Comment by brunobl** [comment] 2017-05-27 10:41
I think this could be done step by step as they did:
https://hexdocs.pm/phoenix/Mix.Tasks.Phoenix.Gen.Model.html

1. Simple Model generator
vapor gen.fluentmodel User name:string age:integer 

2. Model generator with references
vapor gen.fluentmodel Post title user_id:references:User

3. JSON-api generator
vapor gen.jsonapi Post title user_id:references:User

4. Leaf generator
vapor gen.leafhtml User name:string age:integer

**Comment by Joannis** [comment] 2017-09-18 15:43
Obsolete thanks to Codable?

**Comment by steffendsommer** [comment] 2017-09-19 07:44
Although this might not be what you want, but we recently created this repo for sharing our sourcery templates for faster scaffolding of Vapor code: https://github.com/nodes-vapor/sourcery-templates

Sorry for the lack of documentation at this point.

**Comment by brunobl** [comment] 2017-09-23 08:52
Could you precise what you mean? That thanks to Codable, we can hope for
things like automatic REST api for databases and such? This can be good.
But templates would be useful too.

**Comment by Joannis** [comment] 2017-09-23 09:46
@brunobl most of this can be easily taken over using Swift 4's Codables. They generate boilerplate code for your database, JSON and other models.

**Comment by 0xTim** [comment] 2024-01-25 12:09
Closing as a dupe of #397

**Closed by 0xTim** 2024-01-25 12:09 UTC
Labels: enhancement
