### ISSUE TITLE
'vapor docker build' is failed as expecting Swiftenv

### ISSUE THREAD

**Issue by dhamukrish** [vapor/toolbox#98] opened 2016-10-05 16:40 UTC
I have refreshed the project with `vapor docker init & build`  and I am getting below error with latest Vapor Toolbox 1.0.3

`Error: Could not determine Swift version from .swift-version file.`

**Comment by KevinVitale** [comment] 2016-10-14 19:14
Ran into the same issue; it's caused by [this line](https://github.com/vapor/toolbox/blob/master/Sources/VaporToolbox/DockerBuild.swift#L38).

It's a simple fix: create a new file at the root of your application's directory, called `.swift-version`. Edit the so it contains a single line: `3.0`, then save it.

After you've added the  `.swift-version` file, delete your existing `Dockerfile` and run `vapor init` again.

FWIW, I'm confused as to why the `.swift-version` is required if the `Dockerfile` which gets cloned assumes the Swift version regardless.

**Comment by tannernelson** [comment] 2016-10-17 16:40
The docker functionality just needs to be updated. It hasn't been since Swift was in beta.

**Comment by mz2** [comment] 2017-01-26 11:35
I'm a bit confused by this: there's no `3.0-RELEASE` to install via swiftenv – there is however `3.0` (and `3.0.1`, `3.0.2` etc). Is the precise value that should be there still `3.0-RELEASE`? 

What needs  to be done more broadly to update the docker functionality to current form? If this can be itemised, I'm happy to try to delve in and help.

**Comment by mz2** [comment] 2017-01-26 12:00
Ok, I got the Docker image built and running with manually passing in the `SWIFT_VERSION` build argument. Seems to me like the idea of grabbing the version from `.swift-version` and constructing the Swift URL seem rather brittle and verging on too much magic: swiftenv doesn't like `3.0-RELEASE` but wants `3.0`, so including `3.0-RELEASE` in my .swift-version is counter-productive and actually doesn't help presently with getting the thing to build: there's both the `3.0-release` (the branch name) and the same in caps needed in different parts of the Swift tarball URL and given the current failure in the script, I assume there may have been changes at swift.org that cause the issue now. I would think it's just clearer for the user if the full URL to grab the Swift build from would need to be passed in knowingly as an argument to `vapor docker init`, and it was validated at least for the platform bit (i.e. user would be warned if the URL doesn't look like it's for the intended target platform, and similarly could be warned if the .swift-version doesn't match).

**Comment by tannernelson** [comment] 2017-02-02 13:26
This should be fixed by https://github.com/vapor/toolbox/pull/132

**Comment by BrettRToomey** [comment] 2017-05-03 13:33
Closing this due to inactivity. Please feel free to reopen.

**Closed by BrettRToomey** 2017-05-03 13:33 UTC
